### ISSUE TITLE
Proposal: Authentication

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/pyCord#5]
## problem

the bot itself cannot validate if users have used nicknames or are authenticated to nickserv

## solution

add a hidden (secret / password locked) management channel
the main bot communicates with multiple mini bots there

### API

request:
```json
{
  "network": "esper",
  "platform":"irc",
  "command": "identify",
  "data": 
  {
    "name": "randomuser"
  }
```

response

```json
{
  "network": "esper",
  "platform": "irc",
  "command": "identified",
  "data": 
  {
    "username": "randomuser"
  }
}
```
the data does not have to be serialized in json and does not have to be this data structure, especially if no more commands are needed

the main bot can only validate the apparent username of the helper bots and the channel they communicate in, so that has to be secure,
alternatively it could request a challenge on request (public key / private key)

**Comment by ghost** [comment]
seems good but I would like to change the format to something like this:

Request:
```JSON
{
  "network": "esper",
  "platform":"irc",
  "type": "command",
  "command": "identify",
  "data": 
  {
    "nick": "randomuser"
  }
}
```

Response:
```JSON
{
  "network": "esper",
  "platform": "irc",
  "type": "response",
  "command": "identify",
  "data": 
  {
    "nick": "randomuser",
    "status": true
  }
}
```

**Comment by NikkyAI** [comment]
well unless we plan to make the main bot also respond to commands by other bots i think there is no need to clarify that ?
maybe a request id to link a response to a command would be more useful ?

**Comment by NikkyAI** [comment]
and i do plan to make this as lightweight as possible.. tracking the requests i sent and the responses i get will be annoying enough to track

**Comment by NikkyAI** [comment]
turns out this is not practical as a modular approach.. it would be more useful to have such a thing running in parallel writing to files.. but only when it can see the users .. on irc for example it could not .. unless its in the channel
